config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#gallery'
	get '/gallery' => 'static_pages#gallery'
	get '/about' => 'static_pages#about'
	get '/resume' => 'static_pages#resume'
  	get '/contact' => 'static_pages#contact'
  	get 'public/MarcLaforetResume', :to => redirect('/MarcLaforetResume.pdf')
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def gallery
  end

  def resume
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "gallery",    root_path %></li>
        <li><%= link_to "about",    about_path %></li>
        <li><%= link_to "contact", contact_path %></li>
        <li><%= link_to "resume", resume_path %></li>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Marc Laforet</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <h1 class="navbar-text">Marc Laforet</h1>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About',   about_path %></li>
            <li><%= link_to 'Gallery', gallery_path %></li>
            <li><%= link_to 'Resume', resume_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %> 

	<div class="page-header">
        <h1>About Me</h1>
    </div>
    
    <body>
        <%= image_tag("me.jpg", :alt => "rss feed") %>
        <p> I have extensive experience using diverse data analysis techniques to decipher meaningful metrics from datasets. I enjoy a mixture of implementing pre-defined and ad hoc analysis, using R (statistical and visual) and Python (wrangling, cleaning and storing) languages and packages in a test-driven development methodology. I am very comfortable operating in a Unix environment and writing custom scripts in Bash, R and Python. I have previously used these skills at Western University as a Masters student where I used applied mathematics to characterize a genetic dataset for insights. I have extensive experience with text parsing via next-generation sequencing experiments, distribution modelling using Bayesian frameworks and even some experience with machine learning classification. I'm passionate about making sense of large data sets, communicating results in cohesive documents and visualizations with the ultimate goal of helping direct future decisions.</p>
	</body>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %> 
	<div class="page-header">
        <h1>Contact Information</h1>
	</div>
	
	<body>
	    <p class="lead">Email: mlafore05@gmail.com <br> Phone: 226-973-2330</p>
	</body>

app/views/static_pages/gallery.html.erb
<% provide(:title,"Gallery") %> 
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="A gallery of my work="">
    <meta name="Marc_Laforet" content="Gallery">
    <link rel="icon" href="favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://getbootstrap.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script><style type="text/css"></style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	</head>
 
 	<body>

   

      <div class="jumbotron">
        <h1>R&D - Analytical Decision Making</h1>
        <p class="lead">Here is a selection of sample visualizations I coded from raw data. Examples include summarized results from 23 GB of data and advanced statistical analysis such as dimensionality reduction procedures.</p>
        <p><a class="btn btn-lg btn-success" href="http://rpubs.com/mlafore3/180479" role="button">View</a></p>
      </div>
      
      <div class="jumbotron">
        <h1>Quora Challenge - Trend Analysis Machine</h1>
        <p class="lead">Here is the repository of the object oriented machine I wrote in python to solve this challenge.</p>
        <p><a class="btn btn-lg btn-success" href="https://github.com/mlafore3/QuoraTrendAnalyzer" role="button">View</a></p>
      </div>
      
      <div class="jumbotron">
        <h1>Machine Learning Classification</h1>
        <p class="lead">Optimized K-nearest neighbours in a machine learning classification model. Completed using python.</p>
        <p><a class="btn btn-lg btn-success" href="https://gist.github.com/mlafore3/43389c9b7d35cfa0318c8fe0127cc19f" role="button">View</a></p>
      </div>
      
      <div class="jumbotron">
        <h1>Interactive Visualization</h1>
        <p class="lead">Here, I developed a Shiny app to interactively visualize the power of the students t-test. The user can control parameters of the two distributions being compared such as sample sizes, distribution means, etc.</p>
        <p><a class="btn btn-lg btn-success" href="https://marcon-laforet.shinyapps.io/P-value_Distribution_T-test/" role="button">View</a></p>
      </div>
      
       <div class="jumbotron">
        <h1>I coded this website ! </h1>
        <p class="lead">I used a Ruby on Rails framework along with Javascript libraries, HTML5 and CSS with Sass. Distributed using Heroku and Git controlled. </p>
        <p><a class="btn btn-lg btn-success" href="https://bitbucket.org/mlafore3/website/src" role="button">View</a></p>
      </div>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  

	</body>
</html>